// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDC1bbbNUMuotVKpC_VJHtsMQeT8GnlA4',
    appId: '1:215059104741:web:7fb8dce102a14f908ea50c',
    messagingSenderId: '215059104741',
    projectId: 'gaman1',
    authDomain: 'gaman1.firebaseapp.com',
    storageBucket: 'gaman1.firebasestorage.app',
    measurementId: 'G-PG7RMMYP80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnZPl_NbUE3Fs9e6CeMvGrrgEQzkNP4Ek',
    appId: '1:215059104741:android:fbf08b8a848920878ea50c',
    messagingSenderId: '215059104741',
    projectId: 'gaman1',
    storageBucket: 'gaman1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFwGuBCsgV56-th1plfmjDVcDMZJ52wc',
    appId: '1:215059104741:ios:7b9d9e980bdb6df28ea50c',
    messagingSenderId: '215059104741',
    projectId: 'gaman1',
    storageBucket: 'gaman1.firebasestorage.app',
    iosClientId: '215059104741-duv3g0skumq9otjinf78kbcv4r2qv3be.apps.googleusercontent.com',
    iosBundleId: 'com.gaman.gaman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFwGuBCsgV56-th1plfmjDVcDMZJ52wc',
    appId: '1:215059104741:ios:7b9d9e980bdb6df28ea50c',
    messagingSenderId: '215059104741',
    projectId: 'gaman1',
    storageBucket: 'gaman1.firebasestorage.app',
    iosClientId: '215059104741-duv3g0skumq9otjinf78kbcv4r2qv3be.apps.googleusercontent.com',
    iosBundleId: 'com.gaman.gaman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDC1bbbNUMuotVKpC_VJHtsMQeT8GnlA4',
    appId: '1:215059104741:web:211e158c941849a48ea50c',
    messagingSenderId: '215059104741',
    projectId: 'gaman1',
    authDomain: 'gaman1.firebaseapp.com',
    storageBucket: 'gaman1.firebasestorage.app',
    measurementId: 'G-3MBSZE3TCD',
  );
}
